#define REG_DEV_TYPE = 0x00,
#define REG_DEV_VERSION = 0x01,
#define REG_DEV_STATUS = 0x02,

#define REG_INT_STATUS1 = 0x03,
#define REG_INT_STATUS2 = 0x04,
#define REG_INT_ENABLE1 = 0x05,
#define REG_INT_ENABLE2 = 0x06,
#define REG_STATE = 0x07,
#define REG_OPERATION_CONTROL = 0x08,

#define REG_GPIO0_CONF = 0x0B,
#define REG_GPIO1_CONF = 0x0C,
#define REG_GPIO2_CONF = 0x0D,
#define REG_IOPORT_CONF = 0x0E,

#define REG_IF_FILTER_BW = 0x1C,
#define REG_AFC_LOOP_GEARSHIFT_OVERRIDE = 0x1D,
#define REG_AFC_TIMING_CONTROL = 0x1E,
#define REG_CLOCK_RECOVERY_GEARSHIFT = 0x1F,
#define REG_CLOCK_RECOVERY_OVERSAMPLING = 0x20,
#define REG_CLOCK_RECOVERY_OFFSET2 = 0x21,
#define REG_CLOCK_RECOVERY_OFFSET1 = 0x22,
#define REG_CLOCK_RECOVERY_OFFSET0 = 0x23,
#define REG_CLOCK_RECOVERY_TIMING_GAIN1 = 0x24,
#define REG_CLOCK_RECOVERY_TIMING_GAIN0 = 0x25,
#define REG_RSSI = 0x26,
#define REG_RSSI_THRESHOLD = 0x27,

#define REG_AFC_LIMITER = 0x2A,
#define REG_AFC_CORRECTION_READ = 0x2B,

#define REG_DATAACCESS_CONTROL = 0x30,
#define REG_EZMAC_STATUS = 0x31,
#define REG_HEADER_CONTROL1 = 0x32,
#define REG_HEADER_CONTROL2 = 0x33,
#define REG_PREAMBLE_LENGTH = 0x34,
#define REG_PREAMBLE_DETECTION = 0x35,
#define REG_SYNC_WORD3 = 0x36,
#define REG_SYNC_WORD2 = 0x37,
#define REG_SYNC_WORD1 = 0x38,
#define REG_SYNC_WORD0 = 0x39,
#define REG_TRANSMIT_HEADER3 = 0x3A,
#define REG_TRANSMIT_HEADER2 = 0x3B,
#define REG_TRANSMIT_HEADER1 = 0x3C,
#define REG_TRANSMIT_HEADER0 = 0x3D,

#define REG_PKG_LEN = 0x3E,

#define REG_CHECK_HEADER3 = 0x3F,
#define REG_CHECK_HEADER2 = 0x40,
#define REG_CHECK_HEADER1 = 0x41,
#define REG_CHECK_HEADER0 = 0x42,

#define REG_RECEIVED_HEADER3 = 0x47,
#define REG_RECEIVED_HEADER2 = 0x48,
#define REG_RECEIVED_HEADER1 = 0x49,
#define REG_RECEIVED_HEADER0 = 0x4A,

#define REG_RECEIVED_LENGTH = 0x4B,

#define REG_CHARGEPUMP_OVERRIDE = 0x58,
#define REG_DIVIDER_CURRENT_TRIM = 0x59,
#define REG_VCO_CURRENT_TRIM = 0x5A,

#define REG_AGC_OVERRIDE = 0x69,

#define REG_TX_POWER = 0x6D,
#define REG_TX_DATARATE1 = 0x6E,
#define REG_TX_DATARATE0 = 0x6F,

#define REG_MODULATION_MODE1 = 0x70,
#define REG_MODULATION_MODE2 = 0x71,

#define REG_FREQ_DEVIATION = 0x72,
#define REG_FREQ_OFFSET1 = 0x73,
#define REG_FREQ_OFFSET2 = 0x74,
#define REG_FREQBAND = 0x75,
#define REG_FREQCARRIER_H = 0x76,
#define REG_FREQCARRIER_L = 0x77,

#define REG_FREQCHANNEL = 0x79,
#define REG_CHANNEL_STEPSIZE = 0x7A,

#define REG_FIFO = 0x7F
